### ISSUE TITLE
Tentacles Not Finding GCS Storage File

### ISSUE THREAD

**Issue by critterwilson** [GoogleCloudPlatform/cloud-for-marketing#32]
We have been having an issue in executing a BQ -> GA import with tentacles. The problem is that the tentacles-init cloud function can’t find the .csv file containing our data in the right location (see the attached image). 
1. The export to the specified outbound folder works and it triggers the cloud function
2. The file is deleted from the “outbound” folder and placed in “processed/outbound”
3. But then the “init” cloud function can’t find the file using the full path “processed/outbound/filename.csv” in outbound.
4. The configuration specifies the folder “outbound” as the outbound folder.
5. This results in a failed data import in GA saying that it cant find the file.
Does anyone have a solution?

![image](https://user-images.githubusercontent.com/43965806/129979097-7391c9d8-8e91-4d64-a05a-6f414bc1788d.png)

**Comment by lushu** [comment]
Hi,

The log pasted here looks normal to me. Can you paste more logs before this one?

Some explanation of the log pasted here:

1. Any file come to `outbound` would be moved to `processed/outbound/` by the `init` CF before it handles the file. In this way, we can prevent the task being triggered twice due to  the possible duplicated event messages. Only after the file is successfully moved, this `init` CF will handle the file.
2. The moved file `processed/outbound/` would also send out an event message to trigger `init`, however because it is not under the `outbound` folder, the `init` CF would just print the log and quit. You log is this one.

**Comment by critterwilson** [comment]
Due to company privacy restrictions, I am avoiding sharing some of the error messages to preserve anonymity. However, Here is what the upload in GA looks like:

![Screen Shot 2021-08-19 at 10 37 49 AM](https://user-images.githubusercontent.com/43965806/130108748-136f622b-7969-4680-9fe7-038bf101431d.png)

Any idea what could be causing this?

The file that has been uploaded has the following text in it:

> ga:dimension7,ga:metric30
> {"file":"processed/outbound/API[GA]_config[tentaclesga]_blah_000000000000.csv","bucket":"<REDACTED>"}

WE assumed that the skipped event in the previous message was the cause of this error, but perhaps you have a better idea?

**Comment by lushu** [comment]
Thank you for your reply. I can confirm it's due to a bug.

**Comment by critterwilson** [comment]
Is there a version we could rollback to in the mean time?

**Comment by lushu** [comment]
It has been fixed. Please checkout the latest version.

**Comment by critterwilson** [comment]
Thank you so much! I can confirm it is working!
